CREATE DATABASE jrh2006:

USE jrh2006:

CREATE TABLE `vehicles` (
	`id` INT NOT NULL AUTO_INCREMENT , 
	`placa` VARCHAR(200) NULL , 
	`model` VARCHAR(200) NULL , 
	`color` VARCHAR(200) NULL ,
	`create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (`id`)
) ENGINE = MyISAM;